version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    container_name: vanmoof-key-exporter
    ports:
      - "127.0.0.1:3000:3000"
    networks: 
      - proxy_internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanmoof.entryPoints=websecure"
      - "traefik.http.routers.vanmoof.rule=host(`vanmoof.dral.io`)"
      - "traefik.http.routers.vanmoof.tls=true"
      - "traefik.http.routers.vanmoof.service=vanmoof"
      - "traefik.http.services.vanmoof.loadBalancer.server.port=3000"
